package com.example.ailearningapp;

import android.content.Intent;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;
import androidx.navigation.fragment.NavHostFragment;

import com.example.ailearningapp.databinding.FragmentProfileBinding;
import com.example.ailearningapp.model.ShareLinkResponse;
import com.example.ailearningapp.network.ApiClient;
import com.example.ailearningapp.network.dto.ShareLinkRequest;
import com.example.ailearningapp.state.SessionStore;

import java.util.StringJoiner;

public class ProfileFragment extends Fragment {
    private FragmentProfileBinding binding;

    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        binding = FragmentProfileBinding.inflate(inflater, container, false);
        return binding.getRoot();
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        renderProfile();
        binding.shareProfileButton.setOnClickListener(v -> shareProfile());
        binding.backFromProfileButton.setOnClickListener(v ->
                NavHostFragment.findNavController(this).navigateUp());
    }

    private void renderProfile() {
        binding.profileNameText.setText(getString(R.string.profile_name_label, SessionStore.studentName));
        binding.profileEmailText.setText(getString(R.string.profile_email_label,
                SessionStore.currentUserEmail.isEmpty() ? "Not provided" : SessionStore.currentUserEmail));
        binding.profilePlanText.setText(getString(R.string.profile_plan_label, SessionStore.accountTier));

        String interests = SessionStore.interests.isEmpty() ? "Algorithms, Testing" : join(SessionStore.interests);
        binding.profileInterestsText.setText(getString(R.string.profile_interests_label, interests));
    }

    private void shareProfile() {
        ShareLinkRequest request = new ShareLinkRequest();
        request.email = SessionStore.currentUserEmail;
        request.username = SessionStore.studentName;
        request.interests = SessionStore.interests;

        if (SessionStore.currentUserEmail.isEmpty()) {
            shareWithText(buildFallbackShareText(null));
            return;
        }

        ApiClient.getLearningApiService().createShareLink(request).enqueue(new retrofit2.Callback<ShareLinkResponse>() {
            @Override
            public void onResponse(retrofit2.Call<ShareLinkResponse> call, retrofit2.Response<ShareLinkResponse> response) {
                if (!isAdded()) {
                    return;
                }
                String shareUrl = response.body() == null ? null : response.body().shareUrl;
                shareWithText(buildFallbackShareText(shareUrl));
            }

            @Override
            public void onFailure(retrofit2.Call<ShareLinkResponse> call, Throwable t) {
                if (!isAdded()) {
                    return;
                }
                Toast.makeText(requireContext(), R.string.share_link_fallback_notice, Toast.LENGTH_SHORT).show();
                shareWithText(buildFallbackShareText(null));
            }
        });
    }

    private void shareWithText(String shareText) {
        Intent intent = new Intent(Intent.ACTION_SEND);
        intent.setType("text/plain");
        intent.putExtra(Intent.EXTRA_SUBJECT, getString(R.string.share_profile_subject));
        intent.putExtra(Intent.EXTRA_TEXT, shareText);
        startActivity(Intent.createChooser(intent, getString(R.string.share_profile_button)));
    }

    private String buildFallbackShareText(@Nullable String shareUrl) {
        String base = "Student Profile\n"
                + "Name: " + SessionStore.studentName + "\n"
                + "Plan: " + SessionStore.accountTier + "\n"
                + "Interests: " + (SessionStore.interests.isEmpty() ? "Algorithms, Testing" : join(SessionStore.interests)) + "\n";
        if (shareUrl == null || shareUrl.trim().isEmpty()) {
            return base + "Generated by LLM-Enhanced Learning Assistant App.";
        }
        return base + "Public link: " + shareUrl;
    }

    private String join(java.util.List<String> values) {
        StringJoiner joiner = new StringJoiner(", ");
        for (String value : values) {
            joiner.add(value);
        }
        return joiner.toString();
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        binding = null;
    }
}
